travis:
  secure:
    BINSTAR_TOKEN: gfAKtXub/r3HkuH9AlKzUfHYfEGtpEH31UrOo96xxKMoFymU2Y1loUOqpCW1l1w0zvsZ2HItk9Q5oBEGDBmJT7Xn4YB0vGr1SHx7A0pRcSN49IQAj3qgZgyhjqgFc1R70+6QhdtN1SjDUE/3esAtpYCqriaXgruAjsc2PRn1bDBLmlGQzPi/IOsw1YLqXTyOPCmnLeYNrjD7CoHk96H9FwyU49DEPxHxriwnknvzYX/9HR+60VPKIcOQdC7WioFIS5NRN2Jjel3Jtx8w0QZM9FHRfKI1Sc14cJO91+dVAiyXEF2tneXVLTNmagXe1b8ceZJq7Wze98BDGVk5sBv7ZayeLPwnXUnwSp7C3+f8nUB7jDsz8AAczND4RzLOu+9sQGBqiR6fDhHDc0vSoFdssZLfGEDeIIju9S1NkELKgwj3YspAva+wXGRJPbWuWaRBUsH0pd8Ylp3yPy6y0X/37/o8THCkjzz5KF8I+biD7CauOQH1cDeOi08mVR4ncUKJCuTXagZEImJgN6ukLSLDr+PIQPqPM2L8s/C9Bx18jv5EoYqr6TVmoCSQ1Z5tWjb/WF+ieHj+g3/pQ0fD84RkdmX6BRJO7fxnpPrUFAhP+qip7zmzvIDp0g78gDw/92rXaG9sioQHg6sjmKlsBNWaCvHlDqRYKKezxcM027HZ+q8=
bot:
  automerge: true
conda_forge_output_validation: true
